BOARD = zedboard
UBOOT_CONFIG = zed
BOARD_MODEL = em.avnet.com:zed:part0:1.0
PART = xc7z020clg484-1
# CONFIG is the target configuration for the rocket-chip generator
CONFIG ?= DefaultFPGAConfig
# debug net names used by makefile target fpga-images-with-ila-zedboard/boot.bin
DEBUGNET0 ?= 
DEBUGNET1 ?= NoDebugNet1
DEBUGNET2 ?= NoDebugNet2
DEBUGNET3 ?= NoDebugNet3

include ../common/Makefrag
